global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: shardkv
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shardkv-node-1:8080
        labels:
          shardkv_node: node-1
      - targets:
          - shardkv-node-2:8080
        labels:
          shardkv_node: node-2
      - targets:
          - shardkv-node-3:8080
        labels:
          shardkv_node: node-3
